# Tiny Tantrum Games website.
#
# Stage 1 builds the static site (node build-site.js -> dist/). Stage 2 serves
# dist/ with nginx. The image needs no volumes, no database and no secrets:
# a deploy is `git pull` + rebuild.
#
# The Content-Security-Policy is generated by build-site.js (it contains the
# hash of the one inline script), so it is lifted out of dist/_headers here
# rather than written by hand, and can never drift from the pages it guards.

FROM node:22-alpine AS build
WORKDIR /site
COPY build-site.js site.config.json ./
COPY src ./src
RUN node build-site.js \
 && sed -n 's/^ *Content-Security-Policy: \(.*\)$/add_header Content-Security-Policy "\1" always;/p' dist/_headers > /csp.conf \
 && test -s /csp.conf \
 && rm dist/_headers

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/security-headers.conf /etc/nginx/snippets/security-headers.conf
COPY --from=build /csp.conf /etc/nginx/snippets/csp.conf
COPY --from=build /site/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/healthz > /dev/null || exit 1
